platzigram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#from posts import views as posts_views
#from users import views as users_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'posts'), namespace='posts')),#Sirve para agrupar las urls dependiendo del modulo al que pertenezcan
    #path('', posts_views.list_posts, name='feed'),
    #path('posts/new/', posts_views.create_post, name='create_post'),
    
    path('users/', include(('users.urls', 'users'), namespace='users'))
    
    # path('users/login/', users_views.login_view, name='login'),
    # path('users/logout/', users_views.logout_view, name='logout'),
    # path('users/singup/', users_views.singup, name='singup'),
    # path('users/me/profile', users_views.update_profile, name='update_profile')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from posts import views

urlpatterns =[
    path('', views.PostFeedView.as_view(), name='feed'),
    path('posts/new/', views.CreatePostView.as_view(), name='create'), 
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='detail'),   
    path('posts/featured/', TemplateView.as_view(template_name='posts/featured.html'), name='featured')
]

users/urls.py
from django.urls import path
#from django.views.generic import TemplateView

from users import views


urlpatterns = [
    #path('<str:username>/', TemplateView.as_view(template_name='users/detail.html'), name='detail'),
    path('<str:username>/', views.UserDetailView.as_view(), name= 'detail'),
    path('users/login/', views.LoginView.as_view(), name='login'),
    path('users/logout/', views.LogoutView.as_view(), name='logout'),
    path('users/singup/', views.SingupView.as_view(), name='singup'),
    path('users/me/profile', views.UpdateProfileView.as_view(), name='update')
]

users/models.py
from django.db import models
"""En esta clase se extiende de la tabla que viene por default de users de Django"""
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website =  models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    
    picture = models.ImageField(upload_to='users/pictures', blank=True, null= True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateField(auto_now=True)
    
    def __str__(self):
        return self.user.username

users/forms.py
from django import forms

from django.contrib.auth.models import User
from users.models import Profile

class SignupForm(forms.Form):
    username = forms.CharField(min_length=4, max_length=50)
    password = forms.CharField(max_length=70, widget=forms.PasswordInput())
    password_confirmation = forms.CharField(max_length=70, widget=forms.PasswordInput())
    
    first_name =forms.CharField(min_length=2, max_length=50)
    last_name =forms.CharField(min_length=2, max_length=50)
    email = forms.CharField(min_length=6, max_length=70, widget=forms.EmailInput)
    
    def clean_username(self):
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username= username).exists()
        if (username_taken):
            raise forms.ValidationError('El nombre de usuario ya esta en uso')
        return username
    
    def clean(self):
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']
        if password != password_confirmation:
            raise forms.ValidationError('Las contraseñas no coinciden')
        
        return data
    
    def save(self):
        data = self.cleaned_data
        data.pop('password_confirmation')
        user = User.objects.create_user(**data)
        profile = Profile(user= user)
        profile.save()
            
class ProfileForm(forms.Form):
    website = forms.URLField(max_length=200, required=True)
    biography = forms.CharField(max_length=500, required=False)
    phone_number = forms.CharField(max_length=20, required=False)
    picture = forms.ImageField()

users/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView, FormView, UpdateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy

from django.db.utils import IntegrityError

from django.contrib.auth.models import User
from users.models import Profile
from django.contrib.auth.models import User

from users.forms import ProfileForm, SignupForm
from posts.models import Post
from users.models import Profile

class UserDetailView(LoginRequiredMixin, DetailView):
    template_name = 'users/detail.html' 
    slug_field='username' # Para ejecutarse necesita una llave primaria, pero en este ejemplo no se tiene eso
    slug_url_kwarg= 'username'
    queryset = User.objects.all()  
    context_object_name='user' 
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        return context

class UpdateProfileView(LoginRequiredMixin, UpdateView):
    template_name= 'users/update_profile.html'
    model = Profile
    fields= ['website', 'biography', 'phone_number', 'picture']

    def get_object(self):
        return self.request.user.profile
    
    def get_success_url(self):
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username':username})
  
class LoginView(auth_views.LoginView):
    template_name = 'users/login.html'
    redirect_authenticated_user = True
   
"""@login_required
def update_profile(request):
    profile = request.user.profile
    
    if request.method =='POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            profile.website= data ['website']
            profile.phone_number = data['phone_number']
            profile.biography = data['biography']
            profile.picture = data['picture']

            profile.save()
            url = reverse('users:detail', kwargs={'username': request.user.username})
            return redirect (url)          
    else:
        form = ProfileForm()
        
    return render(
        request= request,
        template_name= 'users/update_profile.html',
        context={
            'profile': profile,
            'user': request.user,
            'form': form
        }
    )
    return render(request, 'users/update_profile.html')
"""

"""def login_view(request):
    
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username= username, password= password)
        if user:
            login(request, user)
            return redirect('posts:feed')
        else:
            return render(request, 'users/login.html', {'error': 'Usuario y contraseña invalidos'})
    return render (request, 'users/login.html')"""

class SingupView(FormView):
    template_name = 'users/singup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

"""def singup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('users:login')
    else:
        form = SignupForm()
    return render(
        request = request,
        template_name = 'users/singup.html',
        context={
            'form': form
        }
    )"""

"""@login_required
def logout_view(request):
    logout(request)
    return redirect('users:login')"""
    
class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout view."""
    pass

"""
Esta seria la forma en la que se validaria la información sin tener en cuenta un modelo
def singup(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        password_confirmation = request.POST['password_confirmation']
        
        if password != password_confirmation:
            return render(request, 'users/singup.html', {'error': 'Las contraseñas no coinciden'}) 
        try:
            user = User.objects.create_user(username = username, password= password)
        except IntegrityError:
            return render(request, 'users/singup.html', {'error': 'Nombre de usuario ya existe'})
        
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.email = request.POST['email']
        user.save()
        
        profile = Profile(user=user)
        profile.save()
        return redirect('login')
        
    return render(request, 'users/singup.html')
"""

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static "img/instagram.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Platzigram</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">

            <div class="col-sm-4 d-flex justify-content-center">
                <img
                    src="{{ user.profile.picture.url }}"
                    alt="@{{ user.username}}"
                    class="rounded-circle"
                    width="150px"
                />
            </div>

            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                    {% if user == request.user %}
                        <a
                            href="{% url "users:update" %}"
                            class="ml-5 btn btn-sm btn-outline-info">
                            Edit profile
                        </a>
                    {% else %}
                        <a
                            href=""
                            class="ml-5 btn btn-sm btn-primary">
                            Follow
                        </a>
                    {% endif %}
                </h2>

                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ user.profile.posts_count }}785</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.followers }}1,401</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{user.profile.following }}491</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="" class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/users/login.html
{% extends "users/base.html" %}
{% block head_content %}
<title>Platzigram login</title>
{% endblock %}

{% block container %}

{% if form.error %}
<p class="alert alert-danger">El usuario y la contaseña no coninciden; intenta de nuevo</p>
{% endif %}
<form action="{% url "users:login" %}" method="POST">
    {% csrf_token %}

    <div class="form-group">
        <input type="text" class="form-control" placeholder="Username" name="username">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" placeholder="password" name="password">
    </div>
    <button class="btn btn-primary btn-block mt-5" type="submit">Iniciar sesión</button>
</form>

<p class="mt-4">¿Aún no tienes una cuenta? <a href="{% url 'users:singup' %}" >¡Registrate aqui! </a> </p>
{% endblock %}

templates/users/singup.html
{% extends "users/base.html" %}
{% block head_content %}
<title>Platzigram sing up</title>
{% endblock %}

{% block container %}
<!-- {% if error %}
<p class="alert alert-danger">{{ error }}</p>
{% endif %} -->
<form action="{% url 'users:singup' %}" method="POST">

    {% csrf_token %}
    <!-- <div class="form-group">
        <input type="text" class="form-control" placeholder="Username" name="username" required>
    </div>
    <div class="form-group">
        <input type="password" class="form-control" placeholder="Password" name="password" required>
    </div>
    <div class="form-group">
        <input type="password" class="form-control" placeholder="Password confirmation" name="password_confirmation" required>
    </div>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="First name" name="first_name" required>
    </div>
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Last name" name="last_name" required>
    </div>
    <div class="form-group">
        <input type="email" class="form-control" placeholder="Email address" name="email" required>
    </div> -->
    {{ form.as_p }}
    <button class="btn btn-primary btn-block mt-5">Registrarse</button>
</form>


{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Update profile</title>
<!-- Se puede pasar ese dato de user debido a que esta definido en los middlewares -->

{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <form action="{% url 'users:update' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="media">
                    {% if profile.picture %}
                        <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" width="40" />
                    {% else%}
                        <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="picture"></p>
                    </div>
                </div>
                {% for error in form.picture.errors %}
                <div class="alert alert-danger">
                    <p>Picture: {{error}}</p>
                </div>
                {% endfor %}
                <hr><br>
                {#  #}
                <div class="form-group">
                    <label>Website</label>
                    <input
                        class="form-control {% if form.website.errors %} is-invalid{% endif%}"
                        type="text"
                        name="website"
                        placeholder="Website"
                        value="{% if form.errors%} {{form.website.value}} {% else %} {{ profile.website }} {% endif %}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.website.errors %} {{error}} {%endfor%}
                    </div>
                </div>

                <div class="form-group">
                    <label>Biography</label>
                    <textarea class="form-control {% if form.biography.errors %} is-invalid{% endif%}" name="biography">{% if form.errors%} {{form.biography.value}} {% else %} {{ profile.biography }} {% endif %}
                    </textarea>
                    <div class="invalid-feedback">
                        {% for error in form.biography.errors %} {{error}} {%endfor%}
                    </div>
                </div>

                <div class="form-group">
                    <label>Phone number</label>
                    <input
                        class="form-control {% if form.phone_number.errors %} is-invalid{% endif%}"
                        type="text"
                        name="phone_number"
                        placeholder="Phone number"
                        value="{% if form.errors%} {{form.phone_number.value}} {% else %} {{ profile.phone_number }} {% endif %}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.phone_number.errors %} {{error}} {%endfor%}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}